// chapter2/mvvm/src/TodosTableView.tsx
import { connect } from "react-redux";
import { useEffect } from "react";
import { controller, ActionDispatchers, State } from "./todosController";

type Props = ActionDispatchers & State;

function TodosListView({ toggleTodoDone, startFetchTodos, todos }: Props) {
  useEffect(() => {
    startFetchTodos();
  }, [startFetchTodos]);

  const todoElements = todos.map(({ id, isDone, name }) => (
    <tr key={id}>
      <td>{id}</td>
      <td>{name}</td>
      <td>
        <input type="checkbox" checked={isDone} onChange={() => toggleTodoDone(id)} />
      </td>
    </tr>
  ));

  return (
    <table>
      <tbody>{todoElements}</tbody>
    </table>
  );
}

export default connect(controller.getState, () =>
  controller.getActionDispatchers()
)(TodosListView);

// chapter2/mvvm_angular/src/todo/view/todos-table-view.component.ts
import { Component, OnInit } from "@angular/core";
import { NgRedux, Select } from '@angular-redux2/store';
import { Observable } from "rxjs";
import { controller } from '../todoController';
import { TodoState } from "../model/state/TodoState";
import { AppState } from "../../common/model/state/AppState";

const { startFetchTodos,
  toggleTodoDone } = controller.getActionDispatchers();

@Component({
  selector: 'todos-table-view',
  template: `
    <table>
      <tr *ngFor="let todo of (todoState | async)?.todos">
        <td>{{ todo.id }}</td>
        <td>{{ todo.name }}</td>
        <td>
          <input
            type="checkbox"
            [checked]="todo.isDone"
            (change)="toggleTodoDone(todo.id)"
          />
        </td>
      </tr>
    </table>
  `
})
export class TodosTableView implements OnInit {
  // @ts-ignore
  @Select(controller.getState) todoState: Observable<TodoState>;

  constructor(private ngRedux: NgRedux<AppState>) {}

  ngOnInit(): void {
    startFetchTodos();
  }

  toggleTodoDone(id: number) {
    toggleTodoDone(id);
  }
}
